### ISSUE TITLE
Explanation roles

### ISSUE THREAD

**Issue by rickerd** [tarlepp/symfony-flex-backend#18]
Can you explain what the different roles are and how the api key can be used or retrieved.
Me and my friend are kinda stuck on this.

When to use certain roles and how to properly use the anonymous role.

**Comment by tarlepp** [comment]
Sure, roles are used within this application to restrict access to basic REST methods.

eg. using following in your controller
```
use Actions\User\FindAction;
```

Will give users with `ROLE_USER` access to get all specified resource items via `GET /your_controller` and then if you change that to eg.
```
use Actions\Admin\FindAction;
```

Then that same route requires that user has `ROLE_ADMIN`, and for anon role you could use this:
```
use Actions\Anon\FindAction;
```

And for api keys, you should use `./bin/console api-key:management` command. Use of api keys is similar for JWT token - so you need to use `Authorization` header with value `ApiKey {your-api-key}`.

This did help you?

**Comment by rickerd** [comment]
Hey Tarlepp,

Great explanation!
The certain roles and use of them are clear to me now.
If user "A" has the admin role then he cannot create a user since the root role is needed for this.
Correct or not?

Generating keys and roles are clear too. However if I want to make a user like in a user registration I would need a root role user to do that.
Or can I use an api-key for that? I've tried to use an API key with the root role attached but the endpoint then fails since the api-key is not attached to a user. The blameable trait is blocking that.

Maybe what i'm looking for is a "real world" example with the api to see how certain things are done.
You've already gave me the jwt explanation link on Youtube that was super helpful but i'm struggling 

I hope you understand what I mean. I don't have a application yet so no architecture is made other than this api of you.
And with all the features in your api I'd love to use this because it has everything a basic api needs.

**Comment by tarlepp** [comment]
You can change the role definition within user controller - or create a new controller (eg. RegistrationController) and use different action trait there - and most likely you want to use also another DTO/FormType for that - so that eg. users cannot change their roles by that.

API keys are usually used with server-to-server communication, and all user stuff with JWT. Currently I don't have working example how to use this with eg. angular frontend - but you could look eg. [this](https://github.com/tarlepp/angular-sailsjs-boilerplate) which is using node.js backend - but you could just switch that frontend to use this API - and sure you need to make some changes - also notice that project is quite old...

@work I have multiple real world examples - but those are private repositories so cannot share those with you.

**Comment by rickerd** [comment]
Okay that makes more sense now. I think I was thinking too much in these original controllers and endpoints + traits.

Thanks for making it even clearer for me and other guys. I'm trying to make this API with Docker, if I finish i'll add it to here.

**Comment by tarlepp** [comment]
I should start to dev this project seriously - because I have done docker-compose setup for couple of @work applications that are using this repository as a base - also those contains some bug fixes. But really haven't had time for that :(

And basically with that you only need to clone this repo and run `docker-compose up` command and kaboom your backend (php-fpm, nginx, mysql) is running on your localhost:8000

**Comment by rickerd** [comment]
You've done already so much on this repo. Everything is so nicely done with Symfony.
Maybe add your docker-compose setup to a seperate branch and you, me and other guys could make the dockerized version.

I know about the time problem and when coming home you're also tired I think. But together we can do it.

**Comment by tarlepp** [comment]
one sec I'll try to make docker part a really quickly :D

**Comment by tarlepp** [comment]
Added that docker support quickly to this - might have some problems...

But how to use it:
1) Run `docker-compose up` command
2) That will create php-fpm, nginx and mysql containers that are named; `php`, `nginx` and `mysql` 
3) And your backend is running on `http://localhost:8000` on that point
4) Note that first run time won't create the actual database, so you need to run `docker-compose exec php /bin/bash` command and then inside that container run `./bin/console doctrine:schema:create` command

that should do it :D

**Comment by tarlepp** [comment]
@rickerd so did that "quick" fix for docker stuff help you in your use case?

**Comment by rickerd** [comment]
Yes it's great! Many thanks.
